[package]
name = "bierpc"
version = "1.0.0"
edition = "2024"

[features]
default = ["generic_array_parse"]
generic_array_parse = []

[dependencies]
bier_derive = { version = "1.0.0", git = "https://github.com/MOBSkuchen/bierpc" }
tokio = { version =  "1.49.0", features = ["full"] }
tokio-rustls = { version = "0.26.4" }